### ISSUE TITLE
user ordering breaks with functions

### ISSUE THREAD

**Issue by asher-pembroke** [EnsembleGovServices/kamodo-core#40]
## Describe the bug
Unable to specify the order of arguments when functions are involved.

## To Reproduce (Registration error)

```python
from kamodo import Kamodo
k = Kamodo(verbose=True)
k['x(r,theta,phi)'] = 'r*sin(theta)*cos(phi)'
```
<details> <summary> click to expand error </summary>

```console
args_from_dict: available names odict_keys([])
args_from_dict: r
args_from_dict: theta
args_from_dict: phi


PARSING WITH UNIFY x(r, theta, phi) x(r, theta, phi)  0 <class 'str'>
symbol registry: OrderedDict()
parsed rhs_expr r*sin(theta)*cos(phi)
2
Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_13/526395624.py", line 3, in <module>
    k['x(r,theta,phi)'] = 'r*sin(theta)*cos(phi)'

  File "/kamodo-core/kamodo/kamodo.py", line 640, in __setitem__
    default_inheritance_check(rhs_expr, lhs_expr)

  File "/kamodo-core/kamodo/kamodo.py", line 207, in default_inheritance_check
    raise SyntaxError('Ordering error')

  File "<string>", line unknown
SyntaxError: Ordering error
```

</details>

**Additional context**
The same occurs for lambda functions, so it's not due to numpy

```python
k = Kamodo(f=lambda x,y: y*x**2, verbose=True)
k['g(y,x)'] = 'f'
```
<details> <summary> click to expand error </summary>

```console
registering f with <function <lambda> at 0xffff840f1ca0>
args_from_dict: available names odict_keys([])
symbol arguments: >>> () <class 'tuple'> <<<
free_symbols: >>> [x, y] <class 'list'> <<<
type of rhs symbols: <class 'list'>
replacing f() with f(x, y)
rhs from input func <function <lambda> at 0xffff840f1ca0>
unit str 
args_from_dict: available names odict_keys(['f'])
args_from_dict: y
args_from_dict: x


PARSING WITH UNIFY g(y, x) g(y, x)  0 <class 'str'>
symbol registry: OrderedDict([('f', f(x, y))])
parsed rhs_expr f(x, y)
Traceback (most recent call last):

  File "/opt/conda/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_13/3655600594.py", line 3, in <module>
    k['g(y,x)'] = 'f'

  File "/kamodo-core/kamodo/kamodo.py", line 640, in __setitem__
    default_inheritance_check(rhs_expr, lhs_expr)

  File "/kamodo-core/kamodo/kamodo.py", line 199, in default_inheritance_check
    raise SyntaxError('Ordering error')

  File "<string>", line unknown
SyntaxError: Ordering error
```

</details>

**Comment by asher-pembroke** [comment]
Todo: Add the following test to `kamodo/test_kamodo.py` and make sure it passes:

```python
def test_order_override():
    k = Kamodo(verbose=True)
    k['x(r,theta,phi)'] = 'r*sin(theta)*cos(phi)'
```

**Comment by pythonguru101** [comment]
I have pushed the changes to the new branch Issue-40 to address this issue. If I need to check default_inheritance_check if verbose=True is getting passed in input? If so, then for which order the 2 examples given on this issue page, it should fail?

**Comment by asher-pembroke** [comment]
> If I need to check default_inheritance_check if verbose=True is getting passed in input? 

No, the verbose flag is just for debugging purposes. Usually pytest doesn't print to stdout unless a test happens to fail.  `test_order_override` should pass regardless of what the verbose flag is. The full test should be
```python
def test_order_override():
    k = Kamodo(f=lambda x,y: y*x**2)
    k['g(y,x)'] = 'f' # should register g(y,x)
    assert k.g(3,4) == k.f(4,3)
    assert k.x(1, np.pi/2, 0) == 1.0
    k['x(r,theta,phi)'] = 'r*sin(theta)*cos(phi)' # should register x(r, theta, phi)

```

**Comment by asher-pembroke** [comment]
`x` should have been declared before the assertion. I've updated the above comment to fix the test.
